from django.urls import path, include
from rest_framework.routers import DefaultRouter
# Import all the ViewSets, including the new one
from .views import RegisterView, LoginView, PatientViewSet, DoctorViewSet, PatientDoctorMappingViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'patients', PatientViewSet, basename='patient')
router.register(r'doctors', DoctorViewSet, basename='doctor')
router.register(r'mappings', PatientDoctorMappingViewSet, basename='mapping')

# The API URLs are now determined automatically by the router.
# The auth URLs are added manually.
urlpatterns = [
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    # This line includes all the URLs generated by the router (for patients, doctors, and mappings)
    path('', include(router.urls)),
]

